version: '3.5'

networks:
  oltp:
    name: oltp

services:
    postgres:
        image: mdillon/postgis:10-alpine
        container_name: oltp-postgres
        env_file:
          - ./.env
        ports:
          - "${POSTGRES_PORT:-5432}:5432"
        volumes:
            - ./${POSTGRES_DATA:-pgdata}:/var/lib/postgresql/data/pgdata:cached
        networks:
            - oltp
